token:
  expiration_time: 864000000 
  secret: '{cipher}AYAoyujvRcFtNyAnO0QtNXzndaMgYUJZtqhBH1BEBTpRgJnNH5MEEDzbdk2sqG7eoCGrFZ+wkTzZyPSKpmfXvhQZafycoTUtRhq8ZzK6VAw8x5hP7qRL3r101aurz32U0PyA78aBlkS82OM2vgnRWff0LNSD/dV/tb+LdR1sRSVMyE9Prgz7d+6uqtAEOuQ9Mzglk8pTsNYaAx0d9jNkwvqwnSbA7gIOoOEzIsCl8qvcu30xc9J+59aHO77V46rfHQepjldwj2PbZLH+gDYHKNTQSI3Aff3colG2CYR97H1hZKJ3JEUcvyBgPEjl8IpED4pi9obU6kpTPKiTXp40EiSXvEpmGs0Wji8i5ZkgT2tXSJUkpPbSrv7FI6FQekR8n8R61JOrEuat35KfJ6YxjItP4fZbl+Vps9BltkdRpeDYufyZ4sAoYFUm2xY7QwWYKqSLOmV6UocrBySQ7uc4/ZMSmlCHN15D9rxEUPpueKIJabSo6txfxFmRoFxE3P16jpu7ukhBf+KRbTu7Kyuycnh02Xpt8jR/XiA2nFVeZ9IXWMiR/U5qWRha9NdYrUtCXQdWrkgvkQRbkWngLyU1AYo3HnJLZNp4BdALswcVtiBB6ZD5KvjPuIy5TX4gYXASnws='

gateway:
  ip: 10.0.0.12
