token:
  expiration_time: 864000000 
  secret: '{cipher}AYA/n2pZeH7J6rQlGn5iIqf2uAZeIvJfVsxrb9bM13JvctrwyOsQ0EeMbnAgUTRj/WjTmzV+I6zyFN2HtCJYaplx3wE7FhDZS4S2+fvw9kENuIvkPAfXkCWqeU3y+XDWCz2RKU3AAUsY4HSPIWt3c/+diZE8MT2hb3p4bSCJclu+2+41DmK0SVyvHir1TwWIEoBIj96rR1BU/6mDTvfWNq7cS8/vcS4G8H9Fkw5D4oyhJd6WU0kXuJf00b9Udrjbd9m2W42F8Hb72pXpt6Mob26VpBNyROYDQlzSd+VlaZ+kaAlemMWe88PWn1H/mpr0aLwHYb6fSRd+VPq49eqR/QhL76MXS8JsDAVoACtbm98Q3BFVzDLbQokDLGaGhV+j6fLhWJuPh5xJqL380PuaoqhSr3b5/Gvjy7w/SQzzg5FZAAJxaMWRVAKFmDqfDCEwpm2H3JmbaaLOU2w5MjObQ8fVasMHhJtogKPK0PB0aPn+aJnRVaV0B1Chb5aNzxbZytjt6J/vb++p7hC90s+FXZrsoITjrOOt1dLNGzMW1LEUmyU2hWMcP5aazWpYz41nq0jkf+2alLO5qFbV33rxBh9bjabJBPQpzWRkeilmLREUYxbjjrvJ2fXap1NumbRD1Fw='

gateway:
  ip: 10.0.0.12
  