token:
  expiration_time: 86400000000 
  secret: '{cipher}AYB9H/UZFTHeMEWDBJ9XtpJIIpVCUxQRnKVWeGEJRACijJyPIWwOvlyeOhrDokojX0JYIwtgGrTFw9Y7VC/p2XuLL4Rt0bse9HfwKO1WSpYLoN5ZTI9va/yGRW4lKbZfZ1EEGyNiEM4j56IH9hD1GF5Pp0cTTUUkSYd8c8SvOwrfQT3TvHHxVtEmqgEd3QEUQRHFJ22Jm1wHlPFeD2orxyfj/SoMbtbz3UEZIYWNrCjoOrwhYqu8d5nppbHQDTN2hXF+Q88SvcO9ENSIy3T4T/uUUhwklITQITwlXgilYXCeuPmB9xC0fsKHmEZu4URJMqV+7YeTRf0VP1cCZ08WX79RCryJJTGah/dKWzOcYchHmd59xGaTV0fUL0pS4nDvuKA9kQYMpx4wComy7LU1/Jqqq6GWVy10UrnJXRBaLKWkI4TLDOu8fhpdJw+BrF476UvCz7pXPXmWATjj9hInpn4q4vY4gtsYTDE3npBPF91HU5mPetSXNR0NCL8cgJoZlPVYoCmaF8oSyTu4rbXAYbpWYE/gQZqjaLBFiL7ox0HIgzbb3fHRFgvn7SZlgQZm7u/2OtNM2gh9lG6kiK8JpFatGEhCAkn6bs6cpnetsB/53H2tgnT3sY0dGSoFKFod+0c='

gateway:
  ip: 10.0.0.12
