token:
  expiration_time: 86400000000 
  secret: '{cipher}AYBW3BEx4ziQgHcYKjr0Fyj29N1xyefDu0xsNEHBS8RY/SpaikRjYIpNiVsIbXIFUY5vkoqVCsUvlOxNJzm15XlU36B9qmaTu9y0h1vcOhuZpVQ8T8T7e3gZdKnXVQqLOYRf/McfTk2UQyT3lOOPjBHrFZ1278hLLUkUbSV+Ixj3k/ELNrKA5Y7r9EX26V1hH5iDHePHqw51Ksy6A2O8ukHeWBfwQGtyqIx6gissiINwRUm8CexjesVw58g1r7NWKjvgOppUqALsh1hiyi8uwFPAh/Gub90Xvz6Ulu2QyasDZoL6lvLT4/Vpn80xsQpH3eremJUCGcCvZF1Ni+VieVcXGFCq5WXEHOKefE7cSsDtfd8bW8OD15zS8sddgdD9duC9KH/c9pd+Pca/LvtygwQMQhTgnO4I1SV+sKHMr/rnOzleLvK+eyZ2WMfT1iTWbioCCZ8wnWUl06rg9ATTYT9pIMWTYLNWHDotMbXxird4IxeZBEJHkfKkhMVmSs8zk+uHQsGbUTSbPWAiG7stEwKAjd4LhPwoUuxo9E6yfPk1I2YAC6IomeUiN6Jt0fP6al+8nNBKOiijF0e4sPhU27952XI4wB6zN1FIf+LPlw2L2qB6jMqz1FwNNKjC63Nxywg='

gateway:
  ip: 10.0.0.12
