spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}AYBpvTk4trZlO8REU/5tAoOTeEpQ2+Xtj+gOJ97sAUDFIA/Zs0gRKvUDdf2NeWM7lKp27vahRKO/KsGL7nE4GEO2QKx3hOaKOofD5ouYYv9LQpmSaREwhRNaZ+jJeJZgjb2edsulr2vq0AfA/5CYgatHqrw6YxqE2LpJWaQoD4lxfpXNQ/wH6gIDUOUyT5EjZmMFu3YQ71VILk877jqhr4WvC68RCd+iFnvUo8n4zAL4P8eoyWEJftMSWgb5m/nZ2+/Mb+wWvc+mEUZ9Sos2MjrZhB1o/qOxjuInEusY+rWJKWvXRGoMF6nc88kw3OyN6HC7NFeQbl7ZzZBjKzsErmuqUpAb9ofIGHxj5oZWB0AOGiDm2nUhkNjczEQzi8imnWRWSTvqG8Qb0+JEashvv+ZGbBMd5OjQUeLNEb0MZChEfyQ5UPD7oC9+j1/feQvPkJ09nW7pDr5eJJwf3VFK9N4cUS1kdTrFdJMS48D1/lBEgy+bj1cWmC6cTYt6RAY8k4sbbazvmUb2s2SsovJAmJbkvo/u57JwnR1Jl5QsSl+dhg=='

order-service:
  url: http://127.0.0.1:8000/order-service/%s/orders



