spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}AYBpvTk4trZlO8REU/5tAoOTeEpQ2+Xtj+gOJ97sAUDFIA/Zs0gRKvUDdf2NeWM7lKp27vahRKO/KsGL7nE4GEO2QKx3hOaKOofD5ouYYv9LQpmSaREwhRNaZ+jJeJZgjb2edsulr2vq0AfA/5CYgatHqrw6YxqE2LpJWaQoD4lxfpXNQ/wH6gIDUOUyT5EjZmMFu3YQ71VILk877jqhr4WvC68RCd+iFnvUo8n4zAL4P8eoyWEJftMSWgb5m/nZ2+/Mb+wWvc+mEUZ9Sos2MjrZhB1o/qOxjuInEusY+rWJKWvXRGoMF6nc88kw3OyN6HC7NFeQbl7ZzZBjKzsErmuqUpAb9ofIGHxj5oZWB0AOGiDm2nUhkNjczEQzi8imnWRWSTvqG8Qb0+JEashvv+ZGbBMd5OjQUeLNEb0MZChEfyQ5UPD7oC9+j1/feQvPkJ09nW7pDr5eJJwf3VFK9N4cUS1kdTrFdJMS48D1/lBEgy+bj1cWmC6cTYt6RAY8k4sbbazvmUb2s2SsovJAmJbkvo/u57JwnR1Jl5QsSl+dhg=='

token:
  expiration_time: 86400000000 
  secret: '{cipher}AYBW3BEx4ziQgHcYKjr0Fyj29N1xyefDu0xsNEHBS8RY/SpaikRjYIpNiVsIbXIFUY5vkoqVCsUvlOxNJzm15XlU36B9qmaTu9y0h1vcOhuZpVQ8T8T7e3gZdKnXVQqLOYRf/McfTk2UQyT3lOOPjBHrFZ1278hLLUkUbSV+Ixj3k/ELNrKA5Y7r9EX26V1hH5iDHePHqw51Ksy6A2O8ukHeWBfwQGtyqIx6gissiINwRUm8CexjesVw58g1r7NWKjvgOppUqALsh1hiyi8uwFPAh/Gub90Xvz6Ulu2QyasDZoL6lvLT4/Vpn80xsQpH3eremJUCGcCvZF1Ni+VieVcXGFCq5WXEHOKefE7cSsDtfd8bW8OD15zS8sddgdD9duC9KH/c9pd+Pca/LvtygwQMQhTgnO4I1SV+sKHMr/rnOzleLvK+eyZ2WMfT1iTWbioCCZ8wnWUl06rg9ATTYT9pIMWTYLNWHDotMbXxird4IxeZBEJHkfKkhMVmSs8zk+uHQsGbUTSbPWAiG7stEwKAjd4LhPwoUuxo9E6yfPk1I2YAC6IomeUiN6Jt0fP6al+8nNBKOiijF0e4sPhU27952XI4wB6zN1FIf+LPlw2L2qB6jMqz1FwNNKjC63Nxywg='

order-service:
  url: http://127.0.0.1:8000/order-service/%s/orders



